version: '3'

services:
    mariadb:
        build: ./requiements/mariadb
        image: mariadb
        env_file:
            .env
        networks:
            - inception-network
        restart: always
        # volumes:
        #     - db:/var/lib/mysql
    adminer:
        build: ./requiements/adminer
        image: adminer
        depends_on: 
            - mariadb
        ports:
            - "8080:8080"
        networks:
            - inception-network
        restart: always
    wordpress:
        build: ./requiements/wordpress
        image: wordpress
        depends_on: 
            - mariadb
        networks:
            - inception-network
        env_file:
            .env
        # volumes:
        #   - wordpress:/var/www/html
        restart: always
    nginx:
        build: ./requiements/nginx
        image: nginx
        depends_on: 
            - wordpress
        ports:
            - "443:443"
        env_file:
            .env
        networks:
            - inception-network
        # volumes:
        #   - wordpress:/var/www/html
        restart: always
networks:
     inception-network:

volumes:
    db:
        driver_opts:
            type: none
            device: "/home/yichinos/data"
            o: bind
    wordpress:
        driver_opts:
            type: none
            device: "/home/yichinos/data"
            o: bind