version: '3'

services:
    mariadb:
        build: ./requiements/mariadb
        image: mariadb
        env_file:
            .env
        networks:
            - inception-network
    adminer:
        build: ./requiements/adminer
        image: adminer
        depends_on: 
            - mariadb
        ports:
            - "8080:8080"
        networks:
            - inception-network
    wordpress:
        build: ./requiements/wordpress
        image: wordpress
        depends_on: 
            - mariadb
        networks:
            - inception-network
        env_file:
            .env
        volumes:
          - wp:/var/www/wordpress
    nginx:
        build: ./requiements/nginx
        image: nginx
        depends_on: 
            - wordpress
        ports:
            - "443:443"
        env_file:
            .env
        networks:
            - inception-network
        volumes:
          - wp:/var/www/wordpress
networks:
     inception-network:

volumes:
  wp:
    name: wp_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/wordpress

